In [38]:
import pandas as pd
import numpy as np
import re

file = r"C:\Users\mkreidler\Desktop\Dancy Building CCCH_revised_ungrouped.csv"

df = pd.DataFrame.from_csv(file)

df.reset_index(inplace=True, drop=False)

data = df[["Page Label", "Comments", "# Units", "Space"]].groupby("Comments").sum().reset_index()
#style = re.findall(pattern, string)

#data["Style"] = data["Comments"]

def add_o(base):
    return base + "oooo"

def get_style(base):
    pat = r"[a-zA-Z]+"
    result = re.findall(pat, base)
    return result[0]

def get_style_num(base):
    pat = r"[\d]+"
    return re.findall(pat, base)[0]

data["sqrt"] = data["# Units"].apply(np.sqrt)
data["style"] = data["Comments"].map(get_style)
data["style num"] = data["Comments"].map(get_style_num)

data

   Comments  # Units       sqrt style style num
0       BK1      182  13.490738    BK         1
1        H1       42   6.480741     H         1
2      H10L        1   1.000000     H        10
3      H10R        1   1.000000     H        10
4       H11        1   1.000000     H        11
5      H12L        6   2.449490     H        12
6      H12R        6   2.449490     H        12
7      H13L        6   2.449490     H        13
8      H13R        6   2.449490     H        13
9       H14        6   2.449490     H        14
10      H15       55   7.416198     H        15
11      H16        3   1.732051     H        16
12      H17        3   1.732051     H        17
13      H2L       24   4.898979     H         2
14      H2R       14   3.741657     H         2
15       H3        1   1.000000     H         3
16      H4L        1   1.000000     H         4
17      H4R        1   1.000000     H         4
18      H5L       25   5.000000     H         5
19      H5R       25   5.000000     H         5
20      H6L       25   5.000000     H         6
21      H6R       25   5.000000     H         6
22       H7       25   5.000000     H         7
23      H8L        1   1.000000     H         8
24      H8R        1   1.000000     H         8
25      H9L        1   1.000000     H         9
26      H9R        1   1.000000     H         9