In [19]:
import pandas as pd


file = r"C:\Users\mkreidler\Desktop\120.xlsx"

df = pd.read_excel(file)

df.head()

,PartCode,Length,Width,Height,WtKg,R2.0-01,R2.0-02,Total,truncated,Unnamed: 9
0,TC1-A01-3101,572.0,0,0,0,NaN,1.0,1,TC1-A01,TC1-A01
1,TC1-A01-3102,629.0,0,0,0,NaN,4.0,4,TC1-A01,
2,TC1-A01-3103,610.0,0,0,0,NaN,1.0,1,TC1-A01,NaN
3,TC1-A01-3104,609.5,0,0,0,NaN,1.0,1,TC1-A01,NaN
4,TC1-A01-3105,608.5,0,0,0,NaN,1.0,1,TC1-A01,NaN

In [23]:


def format(x):
    one = x.split("-")[1]
    two = x.split("-")[2][1:]
    return f"{one}-{two}"



df['bv'] = df.PartCode.apply(format)

df.head()

,PartCode,Length,Width,Height,WtKg,R2.0-01,R2.0-02,Total,truncated,Unnamed: 9,bv
0,TC1-A01-3101,572.0,0,0,0,NaN,1.0,1,TC1-A01,TC1-A01,A01-101
1,TC1-A01-3102,629.0,0,0,0,NaN,4.0,4,TC1-A01,,A01-102
2,TC1-A01-3103,610.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-103
3,TC1-A01-3104,609.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-104
4,TC1-A01-3105,608.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-105

In [24]:
#df.to_excel(r"C:\Users\mkreidler\Desktop\120_modified.xlsx")

In [36]:
df.loc[df.bv.duplicated()== False, :]

,PartCode,Length,Width,Height,WtKg,R2.0-01,R2.0-02,Total,truncated,Unnamed: 9,bv
0,TC1-A01-3101,572.0,0,0,0,NaN,1.0,1,TC1-A01,TC1-A01,A01-101
1,TC1-A01-3102,629.0,0,0,0,NaN,4.0,4,TC1-A01,,A01-102
2,TC1-A01-3103,610.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-103
3,TC1-A01-3104,609.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-104
4,TC1-A01-3105,608.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-105
5,TC1-A01-3106,576.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-106
6,TC1-A01-3107,609.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-107
7,TC1-A01-3108,574.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-108
8,TC1-A01-3109,601.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-109
9,TC1-A01-3110,605.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-110
10,TC1-A01-3111,599.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-111
11,TC1-A01-3112,599.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-112
12,TC1-A01-3113,619.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-113
13,TC1-A01-3114,613.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-114
14,TC1-A01-3115,607.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-115
15,TC1-A01-3116,616.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-116
16,TC1-A01-3117,607.0,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-117
17,TC1-A01-3118,609.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-118
18,TC1-A01-3119,574.5,0,0,0,NaN,1.0,1,TC1-A01,NaN,A01-119
19,TC1-A02-3001,549.5,0,0,0,NaN,20.0,20,TC1-A02,TC1-A02,A02-001
20,TC1-A02-3101,549.5,0,0,0,NaN,1.0,1,TC1-A02,NaN,A02-101
21,TC1-A02-3102,549.5,0,0,0,NaN,1.0,1,TC1-A02,NaN,A02-102
22,TC1-A02-3103,549.5,0,0,0,NaN,2.0,2,TC1-A02,NaN,A02-103
23,TC1-A02-3104,549.5,0,0,0,NaN,2.0,2,TC1-A02,NaN,A02-104
24,TC1-A02-3105,549.5,0,0,0,NaN,1.0,1,TC1-A02,NaN,A02-105
25,TC1-A02-3106,549.5,0,0,0,NaN,1.0,1,TC1-A02,NaN,A02-106
26,TC1-A03-3001,447.5,0,0,0,NaN,21.0,21,TC1-A03,TC1-A03,A03-001
27,TC1-A03-3101,447.5,0,0,0,NaN,2.0,2,TC1-A03,NaN,A03-101
28,TC1-A03-3102,447.5,0,0,0,NaN,1.0,1,TC1-A03,NaN,A03-102
29,TC1-A03-3103,447.5,0,0,0,NaN,3.0,3,TC1-A03,NaN,A03-103
...,...,...,...,...,...,...,...,...,...,...,...
104,TC1-A12.1-3104,676.0,0,0,0,2.0,NaN,2,TC1-A12,NaN,A12.1-104
105,TC1-B01-3001,298.5,0,0,0,60.0,NaN,60,TC1-B01,TC1-B01,B01-001
106,TC1-B02-3001,320.5,0,0,0,60.0,NaN,60,TC1-B02,NaN,B02-001
107,TC1-B03-3001,392.0,0,0,0,60.0,NaN,60,TC1-B03,TC1-B03,B03-001
108,TC1-B03-3101,250.5,0,0,0,1.0,NaN,1,TC1-B03,NaN,B03-101
109,TC1-B04-3001,489.0,0,0,0,61.0,NaN,61,TC1-B04,TC1-B04,B04-001
110,TC1-B04-3101,489.0,0,0,0,1.0,NaN,1,TC1-B04,NaN,B04-101
111,TC1-B04-3102,300.0,0,0,0,1.0,NaN,1,TC1-B04,NaN,B04-102
112,TC1-B05-3001,533.5,0,0,0,61.0,NaN,61,TC1-B05,TC1-B05,B05-001
113,TC1-B05-3101,533.5,0,0,0,2.0,NaN,2,TC1-B05,NaN,B05-101
114,TC1-B06-3101,603.0,0,0,0,8.0,NaN,8,TC1-B06,TC1-B06,B06-101
115,TC1-B07-3101,651.0,0,0,0,3.0,NaN,3,TC1-B07,TC1-B07,B07-101
116,TC1-B07-3102,564.0,0,0,0,1.0,NaN,1,TC1-B07,NaN,B07-102
117,TC1-B08-3001,762.0,0,0,0,77.0,NaN,77,TC1-B08,TC1-B08,B08-001
118,TC1-B08-3101,289.0,0,0,0,1.0,NaN,1,TC1-B08,NaN,B08-101
119,TC1-B08-3102,289.5,0,0,0,1.0,NaN,1,TC1-B08,NaN,B08-102
120,TC1-B08-3103,675.0,0,0,0,1.0,NaN,1,TC1-B08,NaN,B08-103
121,TC1-B08-3104,736.5,0,0,0,1.0,NaN,1,TC1-B08,NaN,B08-104
122,TC1-B08-3105,350.5,0,0,0,1.0,NaN,1,TC1-B08,NaN,B08-105
123,TC1-B08-3106,762.0,0,0,0,1.0,NaN,1,TC1-B08,NaN,B08-106
124,TC1-C01-3101,747.5,0,0,0,NaN,12.0,12,TC1-C01,TC1-C01,C01-101
125,TC1-C01-3102,478.5,0,0,0,NaN,1.0,1,TC1-C01,NaN,C01-102
126,TC1-C02-3101,721.0,0,0,0,NaN,44.0,44,TC1-C02,TC1-C02,C02-101
127,TC1-C02-3102,415.0,0,0,0,NaN,1.0,1,TC1-C02,NaN,C02-102
128,TC1-C03-3101,686.0,0,0,0,NaN,17.0,17,TC1-C03,TC1-C03,C03-101
129,TC1-C03-3102,602.5,0,0,0,NaN,1.0,1,TC1-C03,NaN,C03-102
130,TC1-C04-3001,721.0,0,0,0,NaN,27.0,27,TC1-C04,TC1-C04,C04-001
131,TC1-C05-3101,758.0,0,0,0,NaN,18.0,18,TC1-C05,TC1-C05,C05-101
132,TC1-C06-3101,711.0,0,0,0,NaN,18.0,18,TC1-C06,TC1-C06,C06-101
133,TC1-C06-3102,347.5,0,0,0,NaN,1.0,1,TC1-C06,NaN,C06-102