In [113]:
import pandas as pd
import re

ct = r"C:\Users\mkreidler\Desktop\35 w apples to apples\ct19.xlsx"
rh = r"C:\Users\mkreidler\Desktop\35 w apples to apples\rh.xlsx"

ct = pd.read_excel(ct)
rh = pd.read_excel(rh)


rh[["name", "priority_ctrac", "elevation", "swing_drop"]].head()

      name  priority_ctrac elevation swing_drop
442   Q114             1.0      EAST         E1
3707    A3             1.0      EAST         E1
3705   B27             1.0      EAST         E1
3711   8A4             1.0      EAST         E1
3694   B39             1.0      EAST         E1

In [114]:
rh["pre"] = ""
rh["prior_digit"] = ""
rh["elev_letter"] = ""


def get_digit(x):
    x = str(x)
    if x == "SHIPPED":
        return "Shipped"
    else:
        pat = r"(\d{1,10})"
        result = re.search(pattern=pat, string=x)
        if result:
            return result.group(1)
        
        
def get_letter(x):
    x = str(x)
    return list(x)[0]

rh.prior_digit = rh.priority_ctrac.apply(get_digit)
rh.elev_letter = rh.swing_drop.apply(get_letter)

rh.pre = rh.prior_digit + rh.elev_letter
rh[["name", "priority_ctrac", "elevation", "swing_drop", "pre"]]

rh["cumcount"] = rh.groupby(["pre", "name"]).cumcount() +1


rh["concat"] = "(" + rh.pre + ")" + rh["name"] + "[" + rh["cumcount"].map(str) + "]"

rh.concat
rh = rh[["name", "priority_ctrac", "elevation", "swing_drop", "pre", "concat"]]

rh

       name  priority_ctrac elevation swing_drop  pre        concat
442    Q114             1.0      EAST         E1   1E   (1E)Q114[1]
3707     A3             1.0      EAST         E1   1E     (1E)A3[1]
3705    B27             1.0      EAST         E1   1E    (1E)B27[1]
3711    8A4             1.0      EAST         E1   1E    (1E)8A4[1]
3694    B39             1.0      EAST         E1   1E    (1E)B39[1]
3725   8A3A             1.0      EAST         E1   1E   (1E)8A3A[1]
3691   8A3Z             1.0      EAST         E1   1E   (1E)8A3Z[1]
3726   B13A             1.0      EAST         E1   1E   (1E)B13A[1]
3727   B39A             1.0      EAST         E1   1E   (1E)B39A[1]
3709    B13             1.0      EAST         E1   1E    (1E)B13[1]
3706     A3             1.0      EAST         E1   1E     (1E)A3[2]
3708    B13             1.0      EAST         E1   1E    (1E)B13[2]
3703    B27             1.0      EAST         E1   1E    (1E)B27[2]
3704    B13             1.0      EAST         E1   1E    (1E)B13[3]
460    Q116             3.0      EAST         E1   3E   (3E)Q116[1]
3695    B39             1.0      EAST         E1   1E    (1E)B39[2]
3712    8A3             1.0      EAST         E1   1E    (1E)8A3[1]
3702    B13             1.0      EAST         E1   1E    (1E)B13[4]
429   Q115A             3.0      EAST         E1   3E  (3E)Q115A[1]
3732   8A4Z             1.0      EAST         E1   1E   (1E)8A4Z[1]
3722   8A4A             1.0      EAST         E1   1E   (1E)8A4A[1]
3723    A3A             1.0      EAST         E1   1E    (1E)A3A[1]
3728   B27A             1.0      EAST         E1   1E   (1E)B27A[1]
3724   B39A             1.0      EAST         E1   1E   (1E)B39A[2]
459     NF1             3.0      EAST         E1   3E    (3E)NF1[1]
89      S3-             3.0      EAST         E1   3E    (3E)S3-[1]
790     B27             1.0      EAST         E1   1E    (1E)B27[3]
424     B12             1.0      EAST         E1   1E    (1E)B12[1]
473    Q114             1.0      EAST         E1   1E   (1E)Q114[2]
461    Q114             3.0      EAST         E1   3E   (3E)Q114[1]
...     ...             ...       ...        ...  ...           ...
2557    AG2            13.0     SOUTH         S2  13S   (13S)AG2[1]
2300    B35            13.0     SOUTH         S2  13S  (13S)B35[16]
2424    AG3            13.0     SOUTH         S2  13S   (13S)AG3[1]
19      B34            13.0     SOUTH         S2  13S   (13S)B34[5]
18      B30            13.0     SOUTH         S2  13S   (13S)B30[1]
17      B34            13.0     SOUTH         S2  13S   (13S)B34[6]
2370   4B1H            13.0     SOUTH         S2  13S  (13S)4B1H[1]
2366   4B2D            13.0     SOUTH         S2  13S  (13S)4B2D[1]
2369   4B1H            13.0     SOUTH         S2  13S  (13S)4B1H[2]
2368   4B1G            13.0     SOUTH         S2  13S  (13S)4B1G[1]
2367   4B1G            13.0     SOUTH         S2  13S  (13S)4B1G[2]
2371    3C8            13.0     SOUTH         S2  13S   (13S)3C8[1]
721       ?            13.0     SOUTH         S2  13S     (13S)?[1]
174     B35            13.0     SOUTH         S2  13S  (13S)B35[17]
172     B35            13.0     SOUTH         S2  13S  (13S)B35[18]
173     B35            13.0     SOUTH         S2  13S  (13S)B35[19]
171     B35            13.0     SOUTH         S2  13S  (13S)B35[20]
2375   9F1B            13.0     SOUTH         S2  13S  (13S)9F1B[1]
2374   9F2B            13.0     SOUTH         S2  13S  (13S)9F2B[1]
2490    B39            13.0     SOUTH         S2  13S   (13S)B39[1]
2372   9E2B            13.0     SOUTH         S2  13S  (13S)9E2B[1]
2373   9E1B            13.0     SOUTH         S2  13S  (13S)9E1B[1]
2485    B35            13.0     SOUTH         S2  13S  (13S)B35[21]
2486    B35            13.0     SOUTH         S2  13S  (13S)B35[22]
2487    B35            13.0     SOUTH         S2  13S  (13S)B35[23]
2488    B35            13.0     SOUTH         S2  13S  (13S)B35[24]
2489    B35            13.0     SOUTH         S2  13S  (13S)B35[25]
2378    9G2            13.0     SOUTH         S2  13S   (13S)9G2[1]
2379    9G2            13.0     SOUTH         S2  13S   (13S)9G2[2]
2317    9G2            13.0     SOUTH         S2  13S   (13S)9G2[3]

[3213 rows x 6 columns]

In [115]:
ct[["Block ID", "Priority", "UnitQuantity"]]

ct["pre"] = ""

def get_pre(x):
    if x == "SHIPPED":
        return "Shipped"
    else:
        pat = r"(\d{1,10}[a-zA-Z]+)"
        result = re.search(pattern=pat, string=x)
        if result:
            return result.group(1)
        
ct.pre = ct.Priority.apply(get_pre)
        
ct[["Block ID", "Priority", "UnitQuantity", "pre"]]

ct["val"] = 1

ct["cumcount"] = ct.groupby(["pre", "Block ID"]).cumcount() +1

ct[["Block ID", "Priority", "UnitQuantity", "pre", "cumcount"]]

ct["concat"] = "(" + ct.pre + ")" + ct["Block ID"] + "[" + ct["cumcount"].map(str) + "]"


ct = ct[["Block ID", "Priority", "UnitQuantity", "pre", "cumcount", "concat", "Void Status"]]

ct.head()

  Block ID Priority  UnitQuantity pre  cumcount        concat
0     3B4X  6S_D5_2             1  6S         1   (6S)3B4X[1]
1      4A2  6S_D5_1             1  6S         1    (6S)4A2[1]
2    3C10Z     3E_1             1  3E         1  (3E)3C10Z[1]
3    3B11A     3E_1             1  3E         1  (3E)3B11A[1]
4    6A16A     9W_2             1  9W         1  (9W)6A16A[1]

In [117]:
merge = rh.merge(ct, on = "concat", how = "outer")

merge.to_excel(r"C:\Users\mkreidler\Desktop\35 w apples to apples\merge.xlsx")