In [3]:
import pandas as pd

def get_name(text):
    text = text.upper()
    file = r"C:\Users\mkreidler\Desktop\Local Data\35w round values\SPREADSHEET STYLE GUIDE -MAB compiled.xlsx"
    df = pd.read_excel(file)
    #df.description = df.description.apply(clean)
    #df["flag"] = np.where(df['description'].str.contains(text, case=False, na=False), 1, 0)

    df = df.loc[df.name.str.contains(text), :]
    return df


get_name("a12")

     name  length  height  depth  family       description   dwg note
114  5A12  21.625     4.0  11.25    sill   SILL STEP RIGHT  NONE  NaN
136  6A12  13.500    11.0   4.00   quoin             QUOIN  41_1  NaN
316   A12  19.750    12.0   4.00  ashlar            ASHLAR    69  NaN
317  A12A  19.750    12.0   4.00  ashlar  ASHLAR STEEL CHK  69_9  NaN

In [2]:
import pandas as pd



def find_all(style, rnd):

    #file = r"V:\Projects\35 East Wacker\Field Work\BVTC Survey #2\35 Wacker -- Measurement DB.xlsx"
    file = r"C:\Users\mkreidler\Desktop\Local Data\35w round values\SPREADSHEET STYLE GUIDE -MAB compiled.xlsx"
    #df = pd.read_excel(file, sheet_name= "Main")
    df = pd.read_excel(file)
    cols = ["family","description", "name", "length", "height", "depth", "note","dwg"]
    
    df.length = df.length.fillna(0)
    df.height = df.height.fillna(0)
    df.depth = df.depth.fillna(0)
    
    def my_round(x, rnd=rnd):
        """Takes some floating point number
        and rounds to closest base"""
        return rnd * round(x / rnd)
    
    def clean(x):
        return x.strip()
    
    df.family = df.family.apply(clean)
    
    if style == "all":        
        m = df.loc[:, cols]
    else:
        m = df.loc[df.family == style, cols]
        

    m["L"] = m.length.apply(my_round)
    m["H"] = m.height.apply(my_round)
    m["D"] = m.depth.apply(my_round)
    
    m = m.sort_values(["length", "height", "depth", "name"])
    
    return m


#find_all("Ashlar", 1/8)
    

def find_match(style, rnd=1/8, L=0, H=0, D=0):
    df = find_all(style, rnd)
    if L+H+D == 0:
        return df
    def my_round(x, rnd=rnd):
        """Takes some floating point number
        and rounds to closest base"""
        return rnd * round(x / rnd)
    
    L = my_round(L, rnd)
    H = my_round(H, rnd)
    D = my_round(D, rnd)
    
    print(L,H,D)
       
    
    df = df.loc[df.L == L, :]
    df = df.loc[df.H == H, :]
    #df = df.loc[df.D == D, :]
    return df[["family", "description", "name", "length", "height", "depth", "note","dwg"]]

result = find_match(style = "ashlar", 
       rnd = 1,
       L = 21 + 3/16, 
       H = 12, 
       D = 4)

result.loc[ result.height <= 120 , :]
#result

21 12 4

     family       description  name  length  height  depth note   dwg
310  ashlar            ASHLAR  A108  20.875  12.000    4.0  NaN  A108
343  ashlar  ASHLAR STEEL CHK  A25A  21.000  11.875    4.0  NaN  69_1
344  ashlar  ASHLAR STEEL CHK  A25A  21.000  11.875    4.0  NaN  69_1
380  ashlar      ASHLAR GREEN   AG2  21.000  12.000    4.0  NaN  69_7
377  ashlar            ASHLAR    A9  21.250  12.000    4.0  NaN    69
378  ashlar  ASHLAR STEEL CHK   A9A  21.250  12.000    4.0  NaN  69_9

In [8]:
import math as m

m.ceil(530/8)

67

In [161]:
import pandas as pd

file = r"C:\Users\mkreidler\Desktop\Local Data\35w round values\SPREADSHEET STYLE GUIDE -MAB compiled.xlsx"
df = pd.read_excel(file)

families = list(df.family.unique())

for f in families:
    print(f)

band
frieze
header
quoin
sill
column
watertable
jamb
egg and dart
dentil
pilaster
frame
ashlar
arch segment
medallion
infill

In [9]:
import pandas as pd
import numpy as np


def clean(x):
    return str(x).upper()

def get_flags(text):
    text = text.upper()
    file = r"C:\Users\mkreidler\Desktop\Local Data\35w round values\SPREADSHEET STYLE GUIDE -MAB compiled.xlsx"
    df = pd.read_excel(file)
    df.description = df.description.apply(clean)
    df["flag"] = np.where(df['description'].str.contains(text, case=False, na=False), 1, 0)

    df = df.loc[df.flag == 1, :]
    return df

get_flags("sill")

,name,length,height,depth,family,description,dwg,note,flag
23,3A1,24.000,5.7500,7.250,sill,SILL RIGHT,7,NaN,1
24,3A2,22.125,5.7500,11.250,sill,SILL RIGHT,8,NaN,1
25,3A3,24.625,5.7500,7.250,sill,SILL LEFT,9,NaN,1
26,3A4,22.000,5.7500,11.250,sill,SILL RIGHT,3A4,NEVER MADE PART OF CO 11,1
70,4A4,23.250,16.8125,20.750,band,TORUS BAND NOTCH SILL LEFT,25,NaN,1
71,4A5,23.250,16.8125,20.750,band,TORUS BAND NOTCH SILL RIGHT,26,NaN,1
73,4A7,23.250,16.8125,20.750,band,TORUS BAND NOTCH SILL RIGHT,28,NaN,1
75,4A9,23.250,16.8125,20.750,band,TORUS BAND NOTCH SILL LEFT,30,NaN,1
96,4B3F,21.750,5.7500,11.500,sill,SILL,34_3,NaN,1
99,4B3H,22.000,5.7500,11.500,sill,SILL BAND RIGHT,4B3H,NEVER MADE PART OF CO 11,1
100,4B3J,22.000,5.7500,11.500,sill,SILL BAND RIGHT,NONE,SAME AS 4B3H?,1
111,5A10,18.000,4.0000,0.000,sill,SILL SEAT LEFT,NONE,NAME REPEATED,1
113,5A11,18.000,4.0000,12.000,sill,SILL SEAT RIGHT,NONE,NaN,1
114,5A12,21.625,4.0000,11.250,sill,SILL STEP RIGHT,NONE,NaN,1
115,5A13,21.625,4.0000,12.000,sill,SILL SEAT LEFT,NONE,NaN,1
116,5A2,18.000,4.0000,7.375,sill,"SILL 4-1/8"" SEAT LEFT",37_1,NaN,1
118,5A3,17.750,4.0000,12.000,sill,SILL CENTER SEAT,37_3,NaN,1
119,5A4,17.500,4.0000,12.000,sill,SILL,37_2,NaN,1
120,5A5,17.500,4.0000,12.000,sill,SILL,37_4,NaN,1
121,5A6L,17.750,4.0000,12.000,sill,"SILL 5"" SEAT LEFT",5A6L,NEVER MADE PART OF CO 11,1
122,5A6R,17.750,4.0000,12.000,sill,"SILL 4"" SEAT RIGHT",5A6L,NEVER MADE PART OF CO 11,1
123,5A7R,17.250,4.0000,12.000,sill,"SILL 5 ""SEAT RIGHT",5A7R,NEVER MADE PART OF CO 11,1
124,5A8R,18.000,4.0000,12.000,sill,"SILL 4-3/4"" SEAT RIGHT",5A8R,NEVER MADE PART OF CO 11,1
250,9D1,20.500,12.2500,11.500,sill,SPANDREL SILL,82,NaN,1
251,9D10,21.000,12.2500,11.500,sill,SPANDREL SILL,82,NaN,1
252,9D1-B,20.500,12.2500,6.375,sill,SPANDREL SILL-GREEN,81,NaN,1
253,9D2,21.750,12.2500,11.500,sill,SPANDREL SILL,82,NaN,1
254,9D2-B,21.750,12.2500,6.375,sill,SPANDREL SILL- GREEN,81,NaN,1
255,9D3,19.000,12.2500,7.000,sill,SPANDREL SILL DELETED,82_1,NaN,1
256,9D3G,19.000,12.2500,7.000,sill,SPANDREL SILL DELETED,82_1,NaN,1
257,9D4,20.750,12.2500,7.000,sill,SPANDREL SILL DELETED,82_1,NaN,1
258,9D7,20.500,12.2500,6.375,sill,SPANDREL SILL,82_2,NaN,1
259,9D8,21.625,12.2500,6.375,sill,SPANDREL SILL,82_2,NaN,1
260,9D9,19.500,12.2500,11.500,sill,SPANDREL SILL,82,NaN,1
572,S2,21.000,6.5000,20.250,sill,SILL,S2,NaN,1
573,S3,19.250,8.1875,7.875,sill,SILL,S3,NEVER MADE PART OF CO 11,1

In [163]:
import os

path = r"V:\Projects\35 East Wacker\Field Work\35 EAST WACKER DRAWINGS 2020 FIELD WORK PDFS\_All drawing pdfs"

drawings = []
paths = []

for root, dirs, files in os.walk(path):
    #print( root)
    #print( dirs)
    for file in files:
        drawing = file[9:-4].split(".3dm")[0]
        full = os.path.join(root, file)
        #print(drawing, full)
        drawings.append(drawing)
        paths.append(full)

data = pd.DataFrame(list(zip(drawings, paths)), columns=["drawing", "path"])
        
data

         drawing                                               path
0        1-0_2B1  V:\Projects\35 East Wacker\Field Work\35 EAST ...
1       10-0_3Bn  V:\Projects\35 East Wacker\Field Work\35 EAST ...
2      10-1_4B3D  V:\Projects\35 East Wacker\Field Work\35 EAST ...
3      10-2_4B3B  V:\Projects\35 East Wacker\Field Work\35 EAST ...
4      10-3_4B3C  V:\Projects\35 East Wacker\Field Work\35 EAST ...
5      100_9E2-B  V:\Projects\35 East Wacker\Field Work\35 EAST ...
6      102_9E4-B  V:\Projects\35 East Wacker\Field Work\35 EAST ...
7        103_BnA  V:\Projects\35 East Wacker\Field Work\35 EAST ...
8        104_B41  V:\Projects\35 East Wacker\Field Work\35 EAST ...
9        105_B42  V:\Projects\35 East Wacker\Field Work\35 EAST ...
10        106_Bn  V:\Projects\35 East Wacker\Field Work\35 EAST ...
11        107_Bn  V:\Projects\35 East Wacker\Field Work\35 EAST ...
12     108-1_B48  V:\Projects\35 East Wacker\Field Work\35 EAST ...
13     108-2_B49  V:\Projects\35 East Wacker\Field Work\35 EAST ...
14     108-3_BnA  V:\Projects\35 East Wacker\Field Work\35 EAST ...
15      108_B38A  V:\Projects\35 East Wacker\Field Work\35 EAST ...
16     109-0_9C5  V:\Projects\35 East Wacker\Field Work\35 EAST ...
17      11-0_3B4  V:\Projects\35 East Wacker\Field Work\35 EAST ...
18     110-0_9C6  V:\Projects\35 East Wacker\Field Work\35 EAST ...
19     111-0_9C8  V:\Projects\35 East Wacker\Field Work\35 EAST ...
20     112-0_9C9  V:\Projects\35 East Wacker\Field Work\35 EAST ...
21    113-0_9C10  V:\Projects\35 East Wacker\Field Work\35 EAST ...
22     114-0_9G5  V:\Projects\35 East Wacker\Field Work\35 EAST ...
23    115-0_2B1A  V:\Projects\35 East Wacker\Field Work\35 EAST ...
24   116-0_6A2XA  V:\Projects\35 East Wacker\Field Work\35 EAST ...
25   117-0_6A14A  V:\Projects\35 East Wacker\Field Work\35 EAST ...
26      12-0_3B5  V:\Projects\35 East Wacker\Field Work\35 EAST ...
27      12-1_3B6  V:\Projects\35 East Wacker\Field Work\35 EAST ...
28      12-2_3B7  V:\Projects\35 East Wacker\Field Work\35 EAST ...
29     12-3_3B10  V:\Projects\35 East Wacker\Field Work\35 EAST ...
..           ...                                                ...
260         Q110  V:\Projects\35 East Wacker\Field Work\35 EAST ...
261         Q111  V:\Projects\35 East Wacker\Field Work\35 EAST ...
262         Q112  V:\Projects\35 East Wacker\Field Work\35 EAST ...
263         Q113  V:\Projects\35 East Wacker\Field Work\35 EAST ...
264         Q114  V:\Projects\35 East Wacker\Field Work\35 EAST ...
265        Q115A  V:\Projects\35 East Wacker\Field Work\35 EAST ...
266         Q116  V:\Projects\35 East Wacker\Field Work\35 EAST ...
267         Q117  V:\Projects\35 East Wacker\Field Work\35 EAST ...
268         Q118  V:\Projects\35 East Wacker\Field Work\35 EAST ...
269         Q119  V:\Projects\35 East Wacker\Field Work\35 EAST ...
270         Q120  V:\Projects\35 East Wacker\Field Work\35 EAST ...
271         Q121  V:\Projects\35 East Wacker\Field Work\35 EAST ...
272        Q122A  V:\Projects\35 East Wacker\Field Work\35 EAST ...
273         Q123  V:\Projects\35 East Wacker\Field Work\35 EAST ...
274         Q124  V:\Projects\35 East Wacker\Field Work\35 EAST ...
275         Q125  V:\Projects\35 East Wacker\Field Work\35 EAST ...
276           S1  V:\Projects\35 East Wacker\Field Work\35 EAST ...
277           S2  V:\Projects\35 East Wacker\Field Work\35 EAST ...
278           S3  V:\Projects\35 East Wacker\Field Work\35 EAST ...
279           W1  V:\Projects\35 East Wacker\Field Work\35 EAST ...
280          W10  V:\Projects\35 East Wacker\Field Work\35 EAST ...
281          W26  V:\Projects\35 East Wacker\Field Work\35 EAST ...
282          W3L  V:\Projects\35 East Wacker\Field Work\35 EAST ...
283          W3R  V:\Projects\35 East Wacker\Field Work\35 EAST ...
284          W4L  V:\Projects\35 East Wacker\Field Work\35 EAST ...
285          W4R  V:\Projects\35 East Wacker\Field Work\35 EAST ...
286          W5L  V:\Projects\35 East Wacker\Field Work\35 EAST ...
287           W7  V:\Projects\35 East Wacker\Field Work\35 EAST ...
288           W8  V:\Projects\35 East Wacker\Field Work\35 EAST ...
289           W9  V:\Projects\35 East Wacker\Field Work\35 EAST ...

[290 rows x 2 columns]

In [175]:
test = str(df.dwg[2])

data["flag"] = np.where(data['drawing'].str.contains(test, case=False, na=False), 1, 0)
#data["flag"] = np.where(data['drawing'].str.startswith(test), 1, 0)

data.loc[data.flag == 1, :]

         drawing                                               path  flag
2      10-1_4B3D  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
3      10-2_4B3B  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
4      10-3_4B3C  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
6      102_9E4-B  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
8        104_B41  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
9        105_B42  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
12     108-1_B48  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
13     108-2_B49  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
17      11-0_3B4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
22     114-0_9G5  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
25   117-0_6A14A  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
30     12-4_3B11  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
33      14-0_3C1  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
36      17-0_3C4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
42      22-0_4A1  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
43      23-0_4A2  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
44      24-0_4A3  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
45      25-0_4A4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
46      26-0_4A5  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
47      27-0_4A6  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
48      28-0_4A7  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
49      29-0_4A8  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
50          2B14  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
52      30-0_4A9  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
53     31-0_4B1n  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
54     32-0_4B1D  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
55     32-1_4B1E  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
56     33-0_4B2n  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
57     34-0_4B3A  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
58     34-1_4B3E  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
..           ...                                                ...   ...
97          4B3H  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
104    51-4_6B12  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
108     52-4_6C4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
117     53-4_B12  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
122      54_B26A  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
136     62-1_8A4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
137    62-3_8A4A  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
141     64-0_8C2  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
142    64-1_8C2A  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
145     66-0_8C4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
146    66-1_8C4A  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
153    68-4_8C8A  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
158     69-4_AG1  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
159     69-5_AG4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
174          7B4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
176     80-0_9C4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
182     87-0_9G4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
186         8A4Z  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
188         8C4D  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
194     94-0_9E2  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
197       96_9E4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
204         9C4D  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
213         A104  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
225         B104  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
234           C4  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
253         Q104  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
264         Q114  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
274         Q124  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
284          W4L  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1
285          W4R  V:\Projects\35 East Wacker\Field Work\35 EAST ...     1

[83 rows x 3 columns]