In [51]:
import pandas as pd
import re

ct = r"C:\Users\mkreidler\Desktop\35w\ctrac.xlsx"
rh = r"C:\Users\mkreidler\Desktop\35w\rhino.xlsx"

ctrac = pd.read_excel(ct)
rhino = pd.read_excel(rh)

rhino.head()

   name  guid  faulty_count  remediation_count  deduct_count  new_count
0     ?   273           NaN                NaN           NaN      272.0
1   2B1     5           NaN                NaN           NaN        3.0
2  2B10     2           NaN                NaN           NaN        1.0
3  2B11     1           NaN                NaN           NaN        NaN
4  2B12     1           NaN                NaN           NaN        NaN

In [55]:
ctrac.head()

,name,10S,10S_1_RE,10S_RE,10W,10W_1_RE,10W_RE,11S,11S_1_RE,11W,...,8W_RE,9S,9S_1_RE,9S_RE,9W,9W_1,9W_2,9W_RE,SHIPPED,total
0,2B1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
1,2B10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,2B11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,2B12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,2B13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [52]:
merge = rhino.merge(ctrac, on="name", how="outer").fillna(0)

merge.head()

,name,guid,faulty_count,remediation_count,deduct_count,new_count,10S,10S_1_RE,10S_RE,10W,...,8W_RE,9S,9S_1_RE,9S_RE,9W,9W_1,9W_2,9W_RE,SHIPPED,total
0,?,273.0,0.0,0.0,0.0,272.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2B1,5.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
2,2B10,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,2B11,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,2B12,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [53]:

merge["delta"] = merge.guid - merge.total

cols = ["name", "guid", "total", "delta", "faulty_count", "remediation_count", "deduct_count"]
delta = merge[cols][merge.delta != 0 ].reset_index()

delta

,index,name,guid,total,delta,faulty_count,remediation_count,deduct_count
0,0,?,273.0,0.0,273.0,0.0,0.0,0.0
1,1,2B1,5.0,4.0,1.0,0.0,0.0,0.0
2,20,3B11,8.0,6.0,2.0,2.0,0.0,0.0
3,30,3C10,15.0,11.0,4.0,2.0,0.0,0.0
4,41,4A1,2.0,1.0,1.0,0.0,0.0,0.0
5,43,4A2,3.0,2.0,1.0,0.0,0.0,0.0
6,44,4A2?,1.0,0.0,1.0,0.0,0.0,0.0
7,50,4A8,4.0,2.0,2.0,0.0,0.0,0.0
8,52,4B?,1.0,0.0,1.0,0.0,0.0,0.0
9,54,4B1B,22.0,20.0,2.0,0.0,0.0,0.0
10,55,4B1C,7.0,6.0,1.0,0.0,0.0,0.0
11,62,4B1K,1.0,0.0,1.0,0.0,0.0,0.0
12,67,4B2E,1.0,0.0,1.0,0.0,0.0,0.0
13,74,4B3G,1.0,2.0,-1.0,0.0,0.0,0.0
14,85,5A6L,1.0,0.0,1.0,0.0,0.0,0.0
15,86,5A6R,4.0,0.0,4.0,0.0,0.0,0.0
16,126,6B9,2.0,1.0,1.0,0.0,0.0,0.0
17,148,7D4M,3.0,4.0,-1.0,0.0,3.0,0.0
18,151,8A2,74.0,70.0,4.0,0.0,0.0,0.0
19,152,8A2A,28.0,14.0,14.0,11.0,0.0,0.0
20,155,8A3A,1.0,0.0,1.0,1.0,0.0,0.0
21,158,8A4A,1.0,0.0,1.0,1.0,0.0,0.0
22,160,8C1,32.0,31.0,1.0,0.0,0.0,0.0
23,162,8C2,42.0,41.0,1.0,0.0,0.0,0.0
24,166,8C4,28.0,25.0,3.0,1.0,0.0,0.0
25,167,8C4A,22.0,21.0,1.0,0.0,0.0,0.0
26,169,8C5,24.0,21.0,3.0,0.0,0.0,0.0
27,170,8C5A,22.0,21.0,1.0,0.0,0.0,0.0
28,171,8C6,41.0,38.0,3.0,1.0,0.0,0.0
29,172,8C6A,23.0,20.0,3.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...
93,389,EXTRAS;,1.0,0.0,1.0,0.0,0.0,0.0
94,390,H1,1.0,0.0,1.0,0.0,0.0,0.0
95,391,J1,1.0,0.0,1.0,0.0,0.0,0.0
96,393,PA100,1.0,0.0,1.0,0.0,0.0,0.0
97,394,Q?,1.0,0.0,1.0,0.0,0.0,0.0
98,397,Q103,14.0,5.0,9.0,0.0,0.0,0.0
99,399,Q105,1.0,0.0,1.0,0.0,0.0,0.0
100,400,Q106,3.0,1.0,2.0,0.0,0.0,0.0
101,404,Q109,11.0,10.0,1.0,0.0,0.0,0.0
102,406,Q111,8.0,7.0,1.0,0.0,0.0,0.0
103,410,Q118-1,1.0,0.0,1.0,0.0,0.0,0.0
104,411,Q118-2,1.0,0.0,1.0,0.0,0.0,0.0
105,412,Q119,1.0,0.0,1.0,0.0,0.0,0.0
106,413,Q120,2.0,0.0,2.0,0.0,0.0,0.0
107,414,Q121,1.0,0.0,1.0,0.0,0.0,0.0
108,415,S?,2.0,0.0,2.0,0.0,0.0,0.0
109,417,S2,3.0,0.0,3.0,0.0,0.0,0.0
110,418,S2??,2.0,0.0,2.0,0.0,0.0,0.0
111,419,S3?,1.0,0.0,1.0,0.0,0.0,0.0
112,420,W2,2.0,0.0,2.0,0.0,0.0,0.0
113,421,W3L,1.0,0.0,1.0,0.0,0.0,0.0
114,422,W3R,1.0,0.0,1.0,0.0,0.0,0.0
115,423,4B-1K,0.0,1.0,-1.0,0.0,0.0,0.0
116,424,9D1-B,0.0,5.0,-5.0,0.0,0.0,0.0
117,425,9D2-B,0.0,2.0,-2.0,0.0,0.0,0.0
118,426,9E1-B,0.0,7.0,-7.0,0.0,0.0,0.0
119,427,9E2-B,0.0,3.0,-3.0,0.0,0.0,0.0
120,428,9E4-B,0.0,1.0,-1.0,0.0,0.0,0.0
121,429,B48,0.0,1.0,-1.0,0.0,0.0,0.0
122,430,Q103A,0.0,9.0,-9.0,0.0,0.0,0.0

In [54]:
delta.to_excel(r"C:\Users\mkreidler\Desktop\35w\delta.xlsx")