In [21]:
import pandas as pd
import re


file = r"C:\Users\mkreidler\Desktop\rhino2.xlsx"
rhino = pd.read_excel(file)

file2 = r"C:\Users\mkreidler\Desktop\ctrac.xlsx"
ctrac = pd.read_excel(file2)

In [22]:
rhino.head()

,layer,name,zones,guid,x,y,z
0,Model::CHANGE ORDER 5::CO 5 P3 NEW,Q115A,['FLOOR 5'// 'EAST ELEVATION'// 'DROP E1'// 'P...,500305f6-c87b-4d31-a6fe-2dee08837fa6,6055.276138,-88.5,-1710.994434
1,Model::CHANGE ORDER 9::CO9 P6 NEW,4B4A,['FLOOR 20'// 'SOUTH ELEVATION'// 'DROP S5'// ...,dafb6a48-0e69-4fa7-b22a-5dfa30efcd16,-1551.306469,-88.5,226.358817
2,Model::CHANGE ORDER 5::CO 5 P3 NEW,4B1F,['FLOOR 21'// 'EAST ELEVATION'// 'DROP E1'// '...,0e121d15-0514-487c-8017-1b362cbd9c1f,6082.936299,-88.5,344.433324
3,Model::BASE BID::P3 NEW,3B2,['FLOOR 21'// 'SOUTH ELEVATION'// 'DROP S1'// ...,064674eb-6866-400b-8b31-bd4f7ac4a525,87.075733,-88.5,383.323683
4,Model::CHANGE ORDER 9::CO9 P6 NEW,4A2?,['FLOOR 20'// 'SOUTH ELEVATION'// 'DROP S5'// ...,72fd679c-86ff-4a7a-a186-ac72a551b89f,-1601.243115,-88.5,239.666353

In [23]:
ctrac.head()

   name  quantity  length  height  depth description dwg_num      comments
0   2B1         0    23.0   11.50  8.125      FRIEZE   35E-1  BOTTOM RIGHT
1   2B1         2    23.0   11.50  8.125      FRIEZE   35E-1  BOTTOM RIGHT
2  2B10         1    21.0   11.50  6.250      FRIEZE   35E-2     AT CORNER
3  2B11         1    22.5   11.75  8.875      HEADER   35E-4         RIGHT
4  2B11         1    22.5   11.75  8.875      HEADER   35E-4         RIGHT

In [24]:
len(rhino)

3698

In [25]:
len(ctrac)

460

In [26]:
ctrac = ctrac.drop_duplicates("name")
ctrac.head()

   name  quantity  length  height  depth description  dwg_num      comments
0   2B1         0   23.00   11.50  8.125      FRIEZE    35E-1  BOTTOM RIGHT
2  2B10         1   21.00   11.50  6.250      FRIEZE    35E-2     AT CORNER
3  2B11         1   22.50   11.75  8.875      HEADER    35E-4         RIGHT
5  2B12         1   21.75   11.25  8.125      FRIEZE  35E-6-1           NaN
6  2B13         1   10.75   11.25  8.125      FRIEZE  35E-6-2           NaN

In [27]:
rhino_ctrac = rhino.merge(ctrac, how="left", on="name")

len(rhino_ctrac)

3698

In [28]:
rhino_ctrac.to_excel(r"C:\Users\mkreidler\Desktop\35ewacker_rhino_mergeleft_ctrac.xlsx")

In [29]:
ctrac_rhino = rhino.merge(ctrac, how="right", on="name")

len(ctrac_rhino)

3226

In [30]:
merge = rhino.merge(ctrac, how="inner", on="name")

len(merge)

3205

In [31]:
merge

,layer,name,zones,guid,x,y,z,quantity,length,height,depth,description,dwg_num,comments
0,Model::CHANGE ORDER 9::CO9 P6 NEW,4B4A,['FLOOR 20'// 'SOUTH ELEVATION'// 'DROP S5'// ...,dafb6a48-0e69-4fa7-b22a-5dfa30efcd16,-1551.306469,-88.50000,226.358817,1,24.000,5.7500,7.0000,BELT COURSE STD,35E-35,NaN
1,Model::CHANGE ORDER 9::CO9 P6,4B4A,['FLOOR 20'// 'SOUTH ELEVATION'// 'DROP S5'// ...,24b2b906-87ed-431d-bce9-025fa4d06636,-1568.644955,-88.50000,226.466605,1,24.000,5.7500,7.0000,BELT COURSE STD,35E-35,NaN
2,Model::CHANGE ORDER 5::CO 5 P3 NEW,4B1F,['FLOOR 21'// 'EAST ELEVATION'// 'DROP E1'// '...,0e121d15-0514-487c-8017-1b362cbd9c1f,6082.936299,-88.50000,344.433324,2,23.750,12.0000,8.5000,BELT COURSE STD,35E-31,NaN
3,Model::BASE BID::P11,4B1F,['FLOOR 21'// 'SOUTH ELEVATION'// 'DROP S3'// ...,b51de032-1c14-4739-8dd6-fc1007788317,-887.233511,-88.50000,339.961741,2,23.750,12.0000,8.5000,BELT COURSE STD,35E-31,NaN
4,Model::BASE BID::P8,4B1F,['FLOOR 21'// 'SOUTH ELEVATION'// 'DROP S4'// ...,207a3a63-59db-46d2-b072-cd36979b84dd,-968.751968,-88.50000,339.881357,2,23.750,12.0000,8.5000,BELT COURSE STD,35E-31,NaN
5,Model::BASE BID::P3 NEW,3B2,['FLOOR 21'// 'SOUTH ELEVATION'// 'DROP S1'// ...,064674eb-6866-400b-8b31-bd4f7ac4a525,87.075733,-88.50000,383.323683,2,23.250,5.7500,5.5000,BELT COURSE STD,35E-10,NaN
6,Model::BASE BID::P3,3B2,['FLOOR 21'// 'SOUTH ELEVATION'// 'DROP S1'// ...,62e77538-6722-408f-a54d-6857081d5358,18.180732,-88.50000,382.645498,2,23.250,5.7500,5.5000,BELT COURSE STD,35E-10,NaN
7,Model::BASE BID::P3,3B2,['FLOOR 21'// 'SOUTH ELEVATION'// 'DROP S1'// ...,247b8d2f-3da4-4071-9bfc-4bc89881c470,176.607105,-88.50000,383.866004,2,23.250,5.7500,5.5000,BELT COURSE STD,35E-10,NaN
8,Model::CHANGE ORDER 9::CO9 P6 NEW,4A2,['FLOOR 20'// 'SOUTH ELEVATION'// 'DROP S5'// ...,487c0c80-1715-4126-89cf-9df128a1281b,-1559.202289,-88.50000,239.952009,1,21.250,16.8125,20.7500,DECORATIVE BAND,35E-23,NaN
9,Model::CHANGE ORDER 9::CO9 P6,4A2,['FLOOR 20'// 'SOUTH ELEVATION'// 'DROP S5'// ...,e6b07506-b25f-4556-a25b-943f46513409,-1580.493422,-88.50000,239.797167,1,21.250,16.8125,20.7500,DECORATIVE BAND,35E-23,NaN
10,Model::CHANGE ORDER 11::CO11 P6 NEW,4A2,['FLOOR 20'// 'WEST ELEVATION'// 'DROP W1'// '...,8227fbfa-25ed-4c42-a7ee-d33adf8b9511,3814.682202,-88.50000,239.947399,1,21.250,16.8125,20.7500,DECORATIVE BAND,35E-23,NaN
11,Model::CHANGE ORDER 9::CO9 P2 NEW,Q108,['FLOOR 13'// 'EAST ELEVATION'// 'DROP E1'// '...,838b37e0-9a97-4452-ac22-e50d24c70669,6099.875632,-88.50000,-613.779529,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
12,Model::CHANGE ORDER 9::CO9 P2 NEW,Q108,['FLOOR 13'// 'EAST ELEVATION'// 'DROP E1'// '...,6167a1f1-253d-4318-af6f-92cb07e7bea0,6099.875632,-88.50000,-625.196935,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
13,Model::CHANGE ORDER 9::CO9 P2 NEW,Q108,['FLOOR 13'// 'EAST ELEVATION'// 'DROP E1'// '...,655103ae-8145-4572-9284-00e46576c13b,6099.875632,-88.50000,-636.755297,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
14,Model::CHANGE ORDER 9::CO9 P2 NEW,Q108,['FLOOR 15'// 'EAST ELEVATION'// 'DROP E1'// '...,44adc1e5-321d-464c-8c28-b7b7d5aa0af8,6099.630911,-88.50000,-393.355733,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
15,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 15'// 'EAST ELEVATION'// 'DROP E1'// '...,8d9a56c4-b4f7-4156-a923-4adc252b4a33,6099.475808,-88.50000,-381.106893,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
16,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 15'// 'EAST ELEVATION'// 'DROP E1'// '...,487d28f0-0e6d-43a8-b55e-d2a052146fa8,6099.475808,-88.50000,-369.310552,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
17,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 15'// 'EAST ELEVATION'// 'DROP E1'// '...,6c70d0d3-e0a0-485b-bf58-97158e9cdcd0,6099.475808,-88.50000,-357.308527,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
18,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 16'// 'EAST ELEVATION'// 'DROP E1'// '...,c92c0086-c9e2-4b5e-a8df-554ecb3480b6,6099.475808,-88.50000,-346.531198,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
19,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 12'// 'EAST ELEVATION'// 'DROP E1'// '...,7bde075d-74e7-470b-8a21-58193f334cf3,6158.057703,-88.50000,-847.775648,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
20,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 13'// 'EAST ELEVATION'// 'DROP E1'// '...,4aaf7195-2cb8-439e-a01d-7151234d32b3,6160.504687,-88.50000,-613.883953,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
21,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 11'// 'EAST ELEVATION'// 'DROP E1'// '...,d712d4ad-b873-4937-b125-767c883f27eb,6160.069538,-88.50000,-871.433037,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
22,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 15'// 'EAST ELEVATION'// 'DROP E1'// '...,8b829416-9e97-4f25-a7c2-8d8042c25640,6158.627061,-88.50000,-378.944246,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
23,Model::CHANGE ORDER 5::CO 5 P2 NEW,Q108,['FLOOR 15'// 'EAST ELEVATION'// 'DROP E1'// '...,20a32c9f-1552-4c79-9e98-6f397f8e2420,6158.767339,-88.50000,-355.938736,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
24,Model::CHANGE ORDER 5::CO 5 P3 NEW,Q108,['FLOOR 19'// 'EAST ELEVATION'// 'DROP E1'// '...,89060bd9-586c-45cc-b473-000422bd5f35,6189.411478,-88.50000,38.769145,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
25,Model::CHANGE ORDER 5::CO 5 P3 NEW,Q108,['FLOOR 18'// 'EAST ELEVATION'// 'DROP E1'// '...,b7e5f031-9301-4247-8bec-e0d973308ef6,6190.315013,-88.50000,16.180760,4,6.000,12.0000,8.5000,QUOIN,35E-Q108,NaN
26,Model::CHANGE ORDER 5::CO 5 P3 NEW,6B16,['FLOOR 6'// 'EAST ELEVATION'// 'DROP E1'// 'P...,cba982cb-e73a-4d6a-a9fe-a3040b1f2a65,6070.518439,-88.50000,-1586.805975,9,20.500,11.0000,6.5000,FLUTE,35E-51-2,HEADER
27,Model::BASE BID::P12,6B16,['FLOOR 6'// 'SOUTH ELEVATION'// 'DROP S2'// '...,bda7aeac-5dab-4c95-971f-367b8ccda307,-454.077662,-88.50000,-1602.617444,9,20.500,11.0000,6.5000,FLUTE,35E-51-2,HEADER
28,Model::BASE BID::P12,6B16,['FLOOR 6'// 'SOUTH ELEVATION'// 'DROP S2'// '...,b86f3e48-2411-4276-8f5a-f0d390ffc817,-433.033008,-88.50000,-1602.617444,9,20.500,11.0000,6.5000,FLUTE,35E-51-2,HEADER
29,Model::BASE BID::P12,6B16,['FLOOR 6'// 'SOUTH ELEVATION'// 'DROP S2'// '...,980cadaf-eb38-4ed5-a7d5-8e56594d274b,-411.159505,-88.50000,-1602.617444,9,20.500,11.0000,6.5000,FLUTE,35E-51-2,HEADER
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3175,Model::CHANGE ORDER 2::CO2 P4,6C3,['FLOOR 7'// 'WEST ELEVATION'// 'DROP W1'// 'P...,d19f49c6-91d0-4ee0-b744-f78a79c09017,4063.571640,-88.50000,-1474.171910,3,21.125,11.8750,12.6875,LINTEL,35E-13-1,NaN
3176,Model::CHANGE ORDER 2::CO2 P1,6C3,['FLOOR 7'// 'EAST ELEVATION'// 'DROP E1'// 'P...,7d4e32e6-2b2a-4561-af9d-557f77cd701c,5909.093514,-724.88784,-1459.344196,3,21.125,11.8750,12.6875,LINTEL,35E-13-1,NaN
3177,Model::CHANGE ORDER 2::CO2 P6,9C10,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W2'// 'P...,f2e86594-ef55-4829-a37c-2d532d3cb449,3465.012103,-88.50000,-1552.429873,3,5.500,13.2500,11.0000,QUOIN,35E-113,NaN
3178,Model::CHANGE ORDER 2::CO2 P6,9C10,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W2'// 'P...,46e12e7a-7b77-43b4-ab31-5cd3b7f38f59,3464.911766,-88.50000,-1538.884405,3,5.500,13.2500,11.0000,QUOIN,35E-113,NaN
3179,Model::CHANGE ORDER 2::CO2 P6,9C10,['FLOOR 7'// 'WEST ELEVATION'// 'DROP W2'// 'P...,c40ca112-f101-49a2-9cac-813a46876c26,3465.649741,-88.50000,-1486.521955,3,5.500,13.2500,11.0000,QUOIN,35E-113,NaN
3180,Model::CHANGE ORDER 2::CO2 P4,6B17,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W1'// 'P...,f2a2fdfa-21c4-4e39-b966-82f65d16484c,4105.471312,-88.50000,-1602.416851,1,20.875,11.0000,4.0000,FLUTE,35E-48,NaN
3181,Model::CHANGE ORDER 2::CO2 P4,6A11,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W1'// 'P...,59368893-c011-4b40-93c9-c15cdbfc9985,4119.097297,-88.50000,-1591.516062,1,26.000,11.0000,4.0000,FRIEZE,35E-43-1,NaN
3182,Model::CHANGE ORDER 2::CO2 P4,9C9,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W1'// 'P...,dc5818b2-220e-4736-b512-a38256ce695b,4075.595002,-88.50000,-1613.676550,3,5.750,12.2500,16.0000,QUOIN,35E-112,NaN
3183,Model::CHANGE ORDER 2::CO2 P4,9C9,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W1'// 'P...,60c1bb9f-040b-4695-a651-f8563d65f19a,3927.642582,-88.50000,-1613.550075,3,5.750,12.2500,16.0000,QUOIN,35E-112,NaN
3184,Model::CHANGE ORDER 2::CO2 P4,9C9,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W1'// 'P...,e9bf931b-7282-4ab5-a797-0654e7478973,3872.588095,-88.50000,-1613.855934,3,5.750,12.2500,16.0000,QUOIN,35E-112,NaN
3185,Model::CHANGE ORDER 2::CO2 P4,9C8,['FLOOR 7'// 'WEST ELEVATION'// 'DROP W1'// 'P...,db041c89-59b1-4592-adf8-3fc67cfecd52,3923.193493,-88.50000,-1486.596691,1,5.750,12.7500,9.0000,QUOIN,35E-111,NaN
3186,Model::CHANGE ORDER 2::CO2 P4,5B4,['FLOOR 7'// 'WEST ELEVATION'// 'DROP W1'// 'P...,8401500b-5e76-4da2-8e78-de4a0696d4c2,4101.565006,-88.50000,-1446.900598,2,23.750,12.7500,18.0625,BAND,35E-38-3,DECORATIVE
3187,Model::CHANGE ORDER 9::CO9 P4,5B4,['FLOOR 7'// 'WEST ELEVATION'// 'DROP W1'// 'P...,bdecec19-df1a-446b-8aff-f91c66ff4e00,4079.567601,-88.50000,-1446.900598,2,23.750,12.7500,18.0625,BAND,35E-38-3,DECORATIVE
3188,Model::CHANGE ORDER 2::CO2 P9,B5,['FLOOR 4'// 'WEST ELEVATION'// 'DROP W3'// 'P...,d361e97c-c6bd-426b-ab3a-ecc323b46d41,3066.374229,-88.50000,-1902.809796,3,13.000,12.7500,4.0000,QUOIN,35E-53-1,NaN
3189,Model::CHANGE ORDER 2::CO2 P9,B5,['FLOOR 3'// 'WEST ELEVATION'// 'DROP W3'// 'P...,d87a5824-f7ab-436c-b4c1-aef3b0ff15d6,3066.607317,-88.50000,-1928.216403,3,13.000,12.7500,4.0000,QUOIN,35E-53-1,NaN
3190,Model::CHANGE ORDER 2::CO2 P9,B5,['FLOOR 3'// 'WEST ELEVATION'// 'DROP W3'// 'P...,551aa07c-c4c2-4432-9f47-ac8360f162ac,3100.796153,-88.50000,-1953.486412,3,13.000,12.7500,4.0000,QUOIN,35E-53-1,NaN
3191,Model::CHANGE ORDER 11::CO11 P9 NEW,B5,['FLOOR 3'// 'WEST ELEVATION'// 'DROP W3'// 'P...,97c1eda9-741d-4f29-b29c-837f5ff297c0,3106.329937,-88.50000,-1928.504195,3,13.000,12.7500,4.0000,QUOIN,35E-53-1,NaN
3192,Model::CHANGE ORDER 11::CO11 P9 NEW,B5,['FLOOR 3'// 'WEST ELEVATION'// 'DROP W3'// 'P...,9ef99d24-7709-4967-9964-b654a2691ffd,3072.355649,-88.50000,-1953.974394,3,13.000,12.7500,4.0000,QUOIN,35E-53-1,NaN
3193,Model::CHANGE ORDER 2::CO2 P4,6A12,['FLOOR 6'// 'WEST ELEVATION'// 'DROP W1'// 'P...,ce9d7c9f-8b56-42ca-9688-bf1d5c961c5e,4072.768947,-88.50000,-1591.887680,1,13.500,11.0000,4.0000,FRIEZE,35E-41-1,NaN
3194,Model::CHANGE ORDER 2::CO2 P6,B42,['FLOOR 7'// 'WEST ELEVATION'// 'DROP W2'// 'P...,641282a9-8afa-4d1c-b6ec-dc1ff8e7f1b4,3463.729447,-88.50000,-1416.774619,2,10.000,11.7500,6.0000,QUOIN,35E-105,NaN
3195,Model::CHANGE ORDER 2::CO2 P6,B42,['FLOOR 7'// 'WEST ELEVATION'// 'DROP W2'// 'P...,764a2735-8ddc-473b-8ec6-14a3bc5596a0,3463.995135,-88.50000,-1406.410350,2,10.000,11.7500,6.0000,QUOIN,35E-105,NaN
3196,Model::CHANGE ORDER 11::CO11 P3 NEW,3C9,['FLOOR 21'// 'EAST ELEVATION'// 'DROP E1'// '...,b7080702-7501-4abf-82e4-4273f91a8518,5899.749825,-88.50000,372.972471,1,23.250,18.8750,22.8750,CORNICE,35E-18,NaN
3197,Model::CHANGE ORDER 2::CO2 P1,8A4,['FLOOR 4'// 'EAST ELEVATION'// 'DROP E1'// 'P...,d8429084-8efc-4673-9fa6-9a71be4b58e0,5848.003757,-724.88784,-1859.654995,1,13.000,12.0000,4.8750,QUOIN,35E-62-1,ANGLED
3198,Model::CHANGE ORDER 2::CO2 P1,8A3,['FLOOR 5'// 'EAST ELEVATION'// 'DROP E1'// 'P...,f75b2f58-fabb-49ff-b71e-2883def0f31d,5853.780738,-724.88784,-1721.191024,1,25.375,12.0000,4.0000,QUOIN,35E-62,NaN
3199,Model::CHANGE ORDER 2::CO2 P1 FAULTY,8A4A,['FLOOR 5'// 'EAST ELEVATION'// 'DROP E1'// 'P...,348251c3-c89b-4ca1-a1dc-1188a0513020,5846.843873,-724.88784,-1710.661854,1,13.000,12.0000,4.8750,QUOIN,35E-62-3,ANGLED
3200,Model::CHANGE ORDER 2::CO2 P1 FAULTY,8A3A,['FLOOR 4'// 'EAST ELEVATION'// 'DROP E1'// 'P...,81a6d9bf-2337-49cb-95ee-7bfb483770f8,5854.197387,-724.88784,-1847.019990,1,25.375,12.0000,4.0000,QUOIN,35E-62-2,NaN
3201,Model::CHANGE ORDER 2::CO2 P1,6A14A,['FLOOR 6'// 'EAST ELEVATION'// 'DROP E1'// 'P...,5ba8e389-d7d8-4851-86d7-c45f3146accb,5856.180024,-724.88784,-1575.488985,1,19.625,11.0000,4.0000,PANEL,35E-117,NaN
3202,Model::CHANGE ORDER 11::CO11 P2 NEW,Q105,['FLOOR 17'// 'EAST ELEVATION'// 'DROP E1'// '...,385203bf-2af0-4c13-8e58-5fd9e11c3b77,6098.791908,-88.50000,-147.764922,7,5.750,12.0000,8.5000,QUOIN,35E-Q105,NaN
3203,Model::CHANGE ORDER 11::CO11 P1 NEW,E1,['FLOOR 5'// 'EAST ELEVATION'// 'DROP E1'// 'P...,732e5e38-7039-4e8e-8ee0-7b6a275afa44,6155.878160,-88.50000,-1691.624702,1,20.125,6.3750,5.5000,EGG & DART,35E-E1,NaN
3204,Model::CHANGE ORDER 11::CO11 P1 NEW,E1,['FLOOR 5'// 'EAST ELEVATION'// 'DROP E1'// 'P...,086bf3ee-9ef8-4515-8ce1-1b43d2106aeb,6134.587733,-88.50000,-1691.734700,1,20.125,6.3750,5.5000,EGG & DART,35E-E1,NaN

In [32]:
#merge.to_excel(r"C:\Users\mkreidler\Desktop\35ewacker_merge.xlsx")
len(merge)

3205

In [33]:
merge_cut = merge.drop_duplicates("name")
len(merge_cut)

352

In [34]:
#merge_cut.to_excel(r"C:\Users\mkreidler\Desktop\35ewacker_merge_cut.xlsx")

In [35]:
styles = merge_cut.name.tolist()
styles.sort()

print(len(styles))

styles

352

['2B1',
 '2B10',
 '2B11',
 '2B12',
 '2B13',
 '2B1A',
 '2B2',
 '2B3A',
 '2B4',
 '2B5',
 '2B6',
 '2B7',
 '2B8',
 '2B9',
 '3A1',
 '3A2',
 '3A3',
 '3B1',
 '3B10',
 '3B11',
 '3B2',
 '3B3',
 '3B4',
 '3B5',
 '3B6',
 '3B7',
 '3C1',
 '3C10',
 '3C2',
 '3C3',
 '3C4',
 '3C5',
 '3C6',
 '3C7',
 '3C8',
 '3C9',
 '4A1',
 '4A10',
 '4A2',
 '4A3',
 '4A4',
 '4A5',
 '4A6',
 '4A7',
 '4A8',
 '4A9',
 '4B1A',
 '4B1B',
 '4B1C',
 '4B1D',
 '4B1E',
 '4B1F',
 '4B1G',
 '4B1H',
 '4B1J',
 '4B1K',
 '4B2A',
 '4B2B',
 '4B2C',
 '4B2D',
 '4B3A',
 '4B3B',
 '4B3C',
 '4B3D',
 '4B3E',
 '4B3F',
 '4B3G',
 '4B4A',
 '4B4B',
 '4B4C',
 '4B4D',
 '4B4E',
 '5A1',
 '5A2',
 '5A3',
 '5A4',
 '5A5',
 '5B1',
 '5B2',
 '5B3',
 '5B4',
 '6A10A',
 '6A11',
 '6A12',
 '6A13A',
 '6A14A',
 '6A1A',
 '6A2A',
 '6A2XA',
 '6A3',
 '6A3A',
 '6A4A',
 '6A5A',
 '6A6',
 '6A7A',
 '6A8A',
 '6A9A',
 '6B1',
 '6B10',
 '6B11',
 '6B12',
 '6B13',
 '6B15',
 '6B16',
 '6B17',
 '6B2',
 '6B3',
 '6B4',
 '6B5',
 '6B6',
 '6B7',
 '6B8',
 '6B9',
 '6C1',
 '6C2',
 '6C3',
 '6C4',
 '6C5',
 '6C6',
 '6C7',
 '6D1',
 '6D2',
 '6D3',
 '7B1',
 '7B2',
 '7B3',
 '7C1',
 '7C2',
 '7C3',
 '7C4',
 '7D1',
 '7D2',
 '7D3',
 '7D4',
 '7D5',
 '8A1',
 '8A2',
 '8A2A',
 '8A3',
 '8A3A',
 '8A4',
 '8A4A',
 '8C1',
 '8C1A',
 '8C2',
 '8C2A',
 '8C3',
 '8C3A',
 '8C4',
 '8C4A',
 '8C5',
 '8C5A',
 '8C6',
 '8C6A',
 '8C7',
 '8C7A',
 '8C8',
 '8C8A',
 '9C1',
 '9C10',
 '9C2',
 '9C3',
 '9C4',
 '9C5',
 '9C6',
 '9C8',
 '9C9',
 '9D1',
 '9D10',
 '9D2',
 '9D7',
 '9D8',
 '9D9',
 '9E1',
 '9E2',
 '9E3',
 '9E4',
 '9E5',
 '9E6',
 '9E7',
 '9E8',
 '9E9',
 '9F1',
 '9F10',
 '9F11',
 '9F1B',
 '9F2',
 '9F2B',
 '9F3',
 '9F4',
 '9F4B',
 '9F5',
 '9F6',
 '9F7',
 '9F8',
 '9F9',
 '9G1',
 '9G2',
 '9G3',
 '9G4',
 '9G5',
 '9H1',
 '9H2',
 'A1',
 'A10',
 'A101',
 'A103',
 'A10A',
 'A11',
 'A11A',
 'A12',
 'A12A',
 'A13',
 'A13A',
 'A14',
 'A14A',
 'A15',
 'A15A',
 'A16',
 'A16A',
 'A17',
 'A18',
 'A18A',
 'A19',
 'A19A',
 'A2',
 'A20',
 'A20A',
 'A21',
 'A21A',
 'A22',
 'A23',
 'A23A',
 'A24',
 'A24A',
 'A25',
 'A25A',
 'A26',
 'A27',
 'A28',
 'A3',
 'A3A',
 'A4',
 'A4A',
 'A5',
 'A5A',
 'A6',
 'A6A',
 'A7',
 'A7A',
 'A8A',
 'A9',
 'A9A',
 'AG1',
 'AG2',
 'AG3',
 'AG4',
 'AG5',
 'AG6',
 'AR1',
 'B1',
 'B10',
 'B101',
 'B102',
 'B11',
 'B12',
 'B13',
 'B13A',
 'B14',
 'B14A',
 'B15',
 'B15A',
 'B16',
 'B16A',
 'B17',
 'B17A',
 'B18',
 'B18A',
 'B19',
 'B2',
 'B20',
 'B20A',
 'B21',
 'B22',
 'B22A',
 'B23',
 'B23A',
 'B24',
 'B25',
 'B26',
 'B26A',
 'B27',
 'B27A',
 'B28',
 'B28A',
 'B29',
 'B29A',
 'B3',
 'B30',
 'B31',
 'B32',
 'B32A',
 'B33',
 'B34',
 'B34A',
 'B35',
 'B35A',
 'B36',
 'B37',
 'B38',
 'B38A',
 'B39',
 'B39A',
 'B4',
 'B40A',
 'B41',
 'B42',
 'B43',
 'B44',
 'B45',
 'B46',
 'B49',
 'B5',
 'B6',
 'B7',
 'B8',
 'B9',
 'C1',
 'C2',
 'C3',
 'C4',
 'C5',
 'C6',
 'C7',
 'C8',
 'CA1',
 'E1',
 'H1',
 'NF1',
 'Q101',
 'Q103',
 'Q104',
 'Q105',
 'Q106',
 'Q108',
 'Q109',
 'Q110',
 'Q111',
 'Q114',
 'Q116',
 'S1',
 'S2']

In [36]:
cnt = merge[["name","guid"]].groupby("name").count()

cnt

      guid
name
2B1      5
2B10     2
2B11     1
2B12     1
2B13     1
2B1A     1
2B2      1
2B3A     2
2B4      1
2B5      1
2B6      1
2B7      2
2B8      1
2B9      1
3A1      2
3A2      1
3A3      1
3B1      2
3B10     1
3B11     8
3B2      3
3B3      1
3B4      2
3B5      1
3B6      1
3B7      1
3C1      1
3C10    15
3C2      2
3C3      1
...    ...
B5       5
B6       1
B7      13
B8       2
B9       2
C1       7
C2       7
C3       6
C4       7
C5       7
C6       6
C7       1
C8       1
CA1      1
E1       2
H1       1
NF1      1
Q101     2
Q103    14
Q104    14
Q105     1
Q106     3
Q108    15
Q109    11
Q110     9
Q111     8
Q114     3
Q116     1
S1       1
S2       3

[352 rows x 1 columns]

In [37]:
cnt.to_excel(r"C:\Users\mkreidler\Desktop\ExistingStyles.xlsx")