In [3]:
import pandas as pd

file = r"C:\Users\mkreidler\Desktop\fuzzy matching.xlsx"

df = pd.read_excel(file)

In [4]:
round(42352.12423421)

42

In [12]:
round(42352.12423421,-1)

42350.0

In [20]:
def round_ten(x):
    return round(x,-1)

def myround(x, base=25):
    return base * round(x/base)

df["fuzzy_x"] = df.x.apply(myround)

df.groupby("fuzzy_x").count()

         floor  guid  name   x   y   z  survey_name
fuzzy_x
-8150        2     2     2   2   2   2            2
-8125       12    12    12  12  12  12           12
-8100        8     8     8   8   8   8            8
-8075        4     4     4   4   4   4            4
-8050        7     7     7   7   7   7            7
-8025        5     5     5   5   5   5            5
-8000        2     2     2   2   2   2            2
-7975        3     3     3   3   3   3            3
-7950        7     7     7   7   7   7            7
-7925        4     4     4   4   4   4            4
-7900        6     6     6   6   6   6            6
-7875       10    10    10  10  10  10           10
-7850        5     5     5   5   5   5            5
-7825        7     7     7   7   7   7            7
-7800        2     2     2   2   2   2            2
-7775        5     5     5   5   5   5            5
-7750        3     3     3   3   3   3            3
-7725        5     5     5   5   5   5            5
-7700        7     7     7   7   7   7            7
-7675        7     7     7   7   7   7            7
-7650        3     3     3   3   3   3            3
-7625       12    12    12  12  12  12           12
-7600        3     3     3   3   3   3            3
-7575        3     3     3   3   3   3            3
-7550        2     2     2   2   2   2            2
-7525        9     9     9   9   9   9            9
-7500        5     5     5   5   5   5            5
-7475        6     6     6   6   6   6            6
-7450        6     6     6   6   6   6            6
-7425       11    11    11  11  11  11           11
...        ...   ...   ...  ..  ..  ..          ...
 6525        2     2     2   2   2   2            2
 6550        3     3     3   3   3   3            3
 6575        2     2     2   2   2   2            2
 6600        2     2     2   2   2   2            2
 6625        2     2     2   2   2   2            2
 6650        3     3     3   3   3   3            3
 6675        3     3     3   3   3   3            3
 6825        5     5     5   5   5   5            5
 6850        6     6     6   6   6   6            6
 6875        3     3     3   3   3   3            3
 6900        2     2     2   2   2   2            2
 6925        2     2     2   2   2   2            2
 6950        3     3     3   3   3   3            3
 6975        2     2     2   2   2   2            2
 7000        5     5     5   5   5   5            5
 7025       10    10    10  10  10  10           10
 7050        3     3     3   3   3   3            3
 7075        2     2     2   2   2   2            2
 7100        1     1     1   1   1   1            1
 8000        1     1     1   1   1   1            1
 8025        2     2     2   2   2   2            2
 8050        2     2     2   2   2   2            2
 8075        3     3     3   3   3   3            3
 8100        1     1     1   1   1   1            1
 8125        4     4     4   4   4   4            4
 8150        2     2     2   2   2   2            2
 8175        3     3     3   3   3   3            3
 8200        2     2     2   2   2   2            2
 8225        2     2     2   2   2   2            2
 8250        1     1     1   1   1   1            1

[302 rows x 7 columns]

In [21]:
import random

random.seed()