In [19]:
import pandas as pd
import re

path = r"C:\Users\mkreidler\Desktop\Quoins.xlsx"

df = pd.read_excel(path)

data = df[["block_id", "height", "len_a", "len_b", "depth" ]]

data = data[data.block_id.str.match("^Q")]

data[]

    block_id  height  len_a  len_b  depth
24       Q31     NaN    NaN    NaN    NaN
25       Q32   350.0  254.0  375.0    NaN
26       Q33   254.0  566.0  100.0    NaN
27      Q35A   355.0  477.0  487.0    NaN
28       Q36   480.0  630.0  487.0    NaN
85       Q27   400.0  445.0   95.0    NaN
86       Q29   400.0  363.0  363.0    NaN
87       Q30   400.0  100.0  100.0    NaN
88      Q35B     NaN    NaN  487.0    NaN
89      Q35C     NaN    NaN  487.0    NaN
90       Q80     NaN  467.0    NaN    NaN
101      Q25   375.0  515.0  305.0    NaN
102      Q28   400.0  325.0  215.0    NaN
103      Q79   400.0  450.0    NaN    NaN
119       Q1   400.0  430.0  270.0    NaN
120      Q11   400.0  305.0  360.0    NaN
121      Q14   255.0    NaN    NaN    NaN
122      Q15   255.0  215.0  600.0    NaN
123      Q16   400.0  445.0  305.0    NaN
124      Q17   255.0    NaN    NaN    NaN
125      Q18   255.0    NaN    NaN    NaN
126     Q19A   445.0    NaN    NaN    NaN
127     Q19B   445.0    NaN    NaN    NaN
128      Q20   255.0    NaN    NaN    NaN
129     Q21A   406.0  550.0  145.0    0.0
130     Q21B     NaN    NaN    NaN    NaN
131      Q23   300.0    NaN  220.0    NaN
132      Q24   255.0    NaN    NaN    NaN
133      Q26   400.0  485.0  227.0    NaN
134      Q65   400.0    NaN    NaN    NaN
..       ...     ...    ...    ...    ...
324      Q54     NaN    NaN    NaN    NaN
325      Q55     NaN    NaN    NaN    NaN
326      Q56     NaN    NaN    NaN    NaN
327      Q57     NaN    NaN    NaN    NaN
328      Q58     NaN    NaN    NaN    NaN
329      Q59     NaN    NaN    NaN    NaN
330      Q5A   400.0  210.0  445.0    NaN
331      Q5B   400.0  210.0  320.0    NaN
332      Q60     NaN    NaN    NaN    NaN
333      Q61     NaN    NaN    NaN    NaN
334      Q62   400.0  180.0  302.0    NaN
335     Q67A     NaN    NaN    NaN    NaN
336     Q67B     NaN    NaN    NaN    NaN
337     Q67C   250.0    NaN    NaN    NaN
338     Q67D     NaN    NaN    NaN    NaN
339      Q68     NaN    NaN    NaN    NaN
340      Q69     NaN    NaN    NaN    NaN
341     Q70A     NaN    NaN    NaN    NaN
342     Q70B     NaN    NaN    NaN    NaN
343     Q70C   250.0    NaN    NaN    NaN
344      Q71     NaN    NaN    NaN    NaN
345     Q72A     NaN    NaN    NaN    NaN
346      Q74     NaN    NaN    NaN    NaN
347      Q75     NaN    NaN    NaN    NaN
348      Q76     NaN    NaN    NaN    NaN
349      Q77     NaN    NaN    NaN    NaN
350      Q78     NaN    NaN    NaN    NaN
351      Q81   400.0    NaN    NaN    NaN
352      Q82   400.0  610.0  145.0    3.0
353      Q83     NaN    NaN    NaN    NaN

[87 rows x 5 columns]

In [60]:
import re

test = "Q702452345 there is someting goin on heraaa Q  Q123"
pattern = r"^[Q][0-9]*"

a = re.findall(pattern, test)
print(a)

['Q702452345']