In [73]:
import pandas as pd
import re

ct = r"C:\Users\mkreidler\Desktop\35w\ctrac.xlsx"
rh = r"C:\Users\mkreidler\Desktop\35w\rhino.xlsx"
st = r"C:\Users\mkreidler\Desktop\35w\site.xlsx"

ctrac = pd.read_excel(ct)
rhino = pd.read_excel(rh)
site = pd.read_excel(st)

In [74]:
ctrac = ctrac[["Priority", "Block ID", "UnitQuantity"]]

#pd.Series.unique

ctrac

    Priority Block ID  UnitQuantity
0         3S      2B1             1
1      6S_D5      2B1             1
2    6W_D1_1      2B1             1
3       3E_1      2B1             1
4      6W_D1     2B10             1
5       3E_1     2B10             1
6      6W_D1     2B11             1
7      6W_D1     2B12             1
8      6W_D1     2B13             1
9      6S_D5     2B1A             1
10        6S      2B2             1
11        3S     2B3A             1
12    12S_D3     2B3A             1
13        3S      2B4             1
14        3S      2B5             1
15        3S      2B6             1
16       12S      2B7             1
17       13S      2B7             1
18       13S      2B8             1
19     6W_D1      2B9             1
20     6S_D5      3A1             1
21       11S      3A1             1
22        3S      3A2             1
23       11S      3A3             1
24        3S      3B1             1
25      3E_1      3B1             1
26        8W     3B10             1
27        8W     3B11             3
28       11W     3B11             1
29      3E_1     3B11             2
..       ...      ...           ...
953       5S      B39             3
954       7S      B39             3
955      11S      B39             1
956      13S      B39             1
957  SHIPPED      B39             6
958    1S_RE     B39A             3
959    1E_RE     B39A             2
960    2S_RE     B39A             7
961    3S_RE     B39A             4
962    4S_RE     B39A             4
963    5S_RE     B39A             2
964    6S_RE     B39A             1
965  SHIPPED     B39A             7
966       9S       B4             1
967       4S     B40A             1
968   12S_D2      B41             1
969    6W_D2      B42             2
970       9S      B43             1
971       1S      B44             1
972       9S      B45             1
973       9S      B46             1
974       3E      B48             1
975       9S      B49             1
976       9W       B5             3
977       4S       B6             1
978       9W       B7             8
979       1E       B8             1
980       4S       B8             1
981       4S       B9             1
982   12S_D2       B9             1

[983 rows x 3 columns]

In [75]:
ctrac = ctrac.groupby(["Priority", "Block ID"]).sum().reset_index()

In [76]:
ctrac.head()

  Priority Block ID  UnitQuantity
0      10S      9D1             5
1      10S      9D2             7
2      10S      9D8             3
3      10S      9E2            10
4      10S      9E3             2

In [77]:
ctrac["elevation"] = ""
ctrac["re"] = ""

def find_re(x):
    if "RE" in x:
        return "RE"
    else:
        return
    
ctrac.re = ctrac.Priority.apply(find_re)

ctrac.head()

  Priority Block ID  UnitQuantity elevation    re
0      10S      9D1             5            None
1      10S      9D2             7            None
2      10S      9D8             3            None
3      10S      9E2            10            None
4      10S      9E3             2            None

In [78]:
ctrac["p"] = ""

def find_p(x):
    pat = r"([\d]*)[a-zA-Z]*"
    result = re.search(string = x, pattern=pat)
    if result:
        return result.group(1)
    
ctrac.p = ctrac.Priority.apply(find_p)

ctrac.head()

  Priority Block ID  UnitQuantity elevation    re   p
0      10S      9D1             5            None  10
1      10S      9D2             7            None  10
2      10S      9D8             3            None  10
3      10S      9E2            10            None  10
4      10S      9E3             2            None  10

In [79]:


def find_elev(x):
    pat = r"[\d]*([a-zA-Z]*)"
    result = re.search(string = x, pattern=pat)
    if result:
        return result.group(1)
    
ctrac.elevation = ctrac.Priority.apply(find_elev)
ctrac

     Priority Block ID  UnitQuantity elevation    re   p
0         10S      9D1             5         S  None  10
1         10S      9D2             7         S  None  10
2         10S      9D8             3         S  None  10
3         10S      9E2            10         S  None  10
4         10S      9E3             2         S  None  10
5         10S      A19             7         S  None  10
6         10S      B29            10         S  None  10
7         10S      B34             6         S  None  10
8         10S      B35            17         S  None  10
9    10S_1_RE      9F1             2         S    RE  10
10   10S_1_RE      9F2            10         S    RE  10
11   10S_1_RE      9F3             3         S    RE  10
12     10S_RE     B29A             2         S    RE  10
13        10W      9E9             1         W  None  10
14        10W      B17             6         W  None  10
15        10W      B25             1         W  None  10
16        10W      B26             2         W  None  10
17        10W      B37             4         W  None  10
18        10W      B38             3         W  None  10
19   10W_1_RE      9F9             1         W    RE  10
20     10W_RE     B17A             3         W    RE  10
21        11S      3A1             1         S  None  11
22        11S      3A3             1         S  None  11
23        11S      3C3             1         S  None  11
24        11S      3C4             1         S  None  11
25        11S      3C5             1         S  None  11
26        11S      4A3             1         S  None  11
27        11S      4A4             1         S  None  11
28        11S     4B1B             5         S  None  11
29        11S     4B1C             1         S  None  11
..        ...      ...           ...       ...   ...  ..
953   SHIPPED      A15             5   SHIPPED  None
954   SHIPPED     A15A             5   SHIPPED  None
955   SHIPPED      A16            12   SHIPPED  None
956   SHIPPED     A16A            10   SHIPPED  None
957   SHIPPED      A18             5   SHIPPED  None
958   SHIPPED     A18A             8   SHIPPED  None
959   SHIPPED      A19             2   SHIPPED  None
960   SHIPPED     A19A             2   SHIPPED  None
961   SHIPPED      A23             8   SHIPPED  None
962   SHIPPED     A23A             6   SHIPPED  None
963   SHIPPED      A6A             1   SHIPPED  None
964   SHIPPED      AG2             1   SHIPPED  None
965   SHIPPED      AG3             1   SHIPPED  None
966   SHIPPED      B17             9   SHIPPED  None
967   SHIPPED     B17A             7   SHIPPED  None
968   SHIPPED      B20             6   SHIPPED  None
969   SHIPPED     B20A             5   SHIPPED  None
970   SHIPPED      B21             1   SHIPPED  None
971   SHIPPED      B22            10   SHIPPED  None
972   SHIPPED     B22A             7   SHIPPED  None
973   SHIPPED      B25             2   SHIPPED  None
974   SHIPPED      B26             2   SHIPPED  None
975   SHIPPED      B29             2   SHIPPED  None
976   SHIPPED      B34            17   SHIPPED  None
977   SHIPPED     B34A            18   SHIPPED  None
978   SHIPPED      B37             2   SHIPPED  None
979   SHIPPED      B38             4   SHIPPED  None
980   SHIPPED     B38A             4   SHIPPED  None
981   SHIPPED      B39             6   SHIPPED  None
982   SHIPPED     B39A             7   SHIPPED  None

[983 rows x 6 columns]

In [80]:
ctrac.elevation.unique()

array(['S', 'W', 'E', 'SHIPPED'], dtype=object)

In [81]:
ctrac.Priority.unique()

array(['10S', '10S_1_RE', '10S_RE', '10W', '10W_1_RE', '10W_RE', '11S',
       '11S_1_RE', '11W', '11W_1', '11W_1_RE', '11W_RE', '12S',
       '12S_1_RE', '12S_D2', '12S_D3', '12S_RE', '13S', '13S_1_RE',
       '13S_RE', '1E', '1E_1', '1E_RE', '1S', '1S_1', '1S_1_RE', '1S_RE',
       '2E', '2E_1', '2E_RE', '2S', '2S_1_RE', '2S_RE', '3E', '3E_1',
       '3E_RE', '3S', '3S_1', '3S_RE', '4S', '4S_1', '4S_1_RE', '4S_RE',
       '4W', '4W_1', '4W_RE', '5S', '5S_1', '5S_1_RE', '5S_RE', '5W',
       '5W_RE', '6S', '6S_1_RE', '6S_D4', '6S_D5', '6S_D5_1', '6S_D5_RE',
       '6S_RE', '6W', '6W_D1', '6W_D1_1', '6W_D1_RE', '6W_D2', '6W_D2_1',
       '6W_RE', '7S', '7S_1_RE', '7W', '7W_1_RE', '7W_RE', '8S', '8S_1',
       '8S_1_RE', '8S_RE', '8W', '8W_RE', '9S', '9S_1_RE', '9S_RE', '9W',
       '9W_1', '9W_RE', 'SHIPPED'], dtype=object)

In [82]:
ctrac["batch"] = ""

def find_batch(x):
    pat = r"[_]([\d]*)[_]"
    result = re.search(string = x, pattern=pat)
    if result:
        return result.group(1)
    
ctrac.batch = ctrac.Priority.apply(find_batch)

In [83]:
ctrac[ctrac.batch.isna() == False]

     Priority Block ID  UnitQuantity elevation  re   p batch
9    10S_1_RE      9F1             2         S  RE  10     1
10   10S_1_RE      9F2            10         S  RE  10     1
11   10S_1_RE      9F3             3         S  RE  10     1
19   10W_1_RE      9F9             1         W  RE  10     1
52   11S_1_RE      9F2             1         S  RE  11     1
65   11W_1_RE      9F7             1         W  RE  11     1
69   12S_1_RE      9F1             4         S  RE  12     1
70   12S_1_RE      9F2             9         S  RE  12     1
71   12S_1_RE      9F3             6         S  RE  12     1
139  13S_1_RE      9F1             3         S  RE  13     1
140  13S_1_RE      9F2             2         S  RE  13     1
232   1S_1_RE     7D4M             4         S  RE   1     1
233   1S_1_RE      9F3             1         S  RE   1     1
234   1S_1_RE     A21G             1         S  RE   1     1
235   1S_1_RE     B18G             6         S  RE   1     1
317   2S_1_RE      9F1             2         S  RE   2     1
318   2S_1_RE      9F2             2         S  RE   2     1
319   2S_1_RE      9F3             2         S  RE   2     1
508   4S_1_RE      9F1             2         S  RE   4     1
509   4S_1_RE      9F2             1         S  RE   4     1
606   5S_1_RE      9F1             2         S  RE   5     1
607   5S_1_RE      9F2             2         S  RE   5     1
608   5S_1_RE      9F3             1         S  RE   5     1
653   6S_1_RE      9F3             1         S  RE   6     1
781   7S_1_RE      9F1             4         S  RE   7     1
782   7S_1_RE      9F2             4         S  RE   7     1
783   7S_1_RE      9F3             3         S  RE   7     1
784   7S_1_RE      9F4             3         S  RE   7     1
785   7S_1_RE      9F5             2         S  RE   7     1
786   7S_1_RE      9F6             1         S  RE   7     1
800   7W_1_RE      9F9             1         W  RE   7     1
819   8S_1_RE      9F1             1         S  RE   8     1
820   8S_1_RE      9F2             2         S  RE   8     1
821   8S_1_RE      9F3             1         S  RE   8     1
822   8S_1_RE      9F4             1         S  RE   8     1
823   8S_1_RE      9F5             1         S  RE   8     1
824   8S_1_RE      9F6             1         S  RE   8     1
874   9S_1_RE      9F2             2         S  RE   9     1
875   9S_1_RE      9F3             1         S  RE   9     1

In [84]:
ctrac["swing_drop"] = ""

def find_drop(x):
    pat = r"[_][D]([\d]*)"
    result = re.search(string = x, pattern=pat, flags=re.IGNORECASE)
    if result:
        return result.group(1)
    
ctrac.swing_drop = ctrac.Priority.apply(find_drop)
ctrac.swing_drop.unique()

array([None, '2', '3', '4', '5', '1'], dtype=object)

In [86]:
ctrac[ctrac.swing_drop.isna() == False]

     Priority Block ID  UnitQuantity elevation    re   p batch swing_drop
72     12S_D2     6A3A             2         S  None  12  None          2
73     12S_D2     6A5A             2         S  None  12  None          2
74     12S_D2     6B16             9         S  None  12  None          2
75     12S_D2      6C2             1         S  None  12  None          2
76     12S_D2      6D3             1         S  None  12  None          2
77     12S_D2      7D1             1         S  None  12  None          2
78     12S_D2      7D2             1         S  None  12  None          2
79     12S_D2      7D3             1         S  None  12  None          2
80     12S_D2      7D4            11         S  None  12  None          2
81     12S_D2      7D5             3         S  None  12  None          2
82     12S_D2      9E1             5         S  None  12  None          2
83     12S_D2      9E2             9         S  None  12  None          2
84     12S_D2      9E3             8         S  None  12  None          2
85     12S_D2     9F10             2         S  None  12  None          2
86     12S_D2     9F11             1         S  None  12  None          2
87     12S_D2      A10             1         S  None  12  None          2
88     12S_D2     A10A             5         S  None  12  None          2
89     12S_D2     A11A             2         S  None  12  None          2
90     12S_D2      A19             3         S  None  12  None          2
91     12S_D2      AG2             3         S  None  12  None          2
92     12S_D2      AG3             2         S  None  12  None          2
93     12S_D2      B17             1         S  None  12  None          2
94     12S_D2      B18             2         S  None  12  None          2
95     12S_D2      B29            26         S  None  12  None          2
96     12S_D2      B34            14         S  None  12  None          2
97     12S_D2      B35            49         S  None  12  None          2
98     12S_D2      B36             4         S  None  12  None          2
99     12S_D2      B41             1         S  None  12  None          2
100    12S_D2       B9             1         S  None  12  None          2
101    12S_D3     2B3A             1         S  None  12  None          3
..        ...      ...           ...       ...   ...  ..   ...        ...
740  6W_D1_RE     8C4D             1         W    RE   6  None          1
741  6W_D1_RE     9C6A             1         W    RE   6  None          1
742  6W_D1_RE     9F7D             1         W    RE   6  None          1
743  6W_D1_RE     9F8D             1         W    RE   6  None          1
744  6W_D1_RE     A6AF             1         W    RE   6  None          1
745  6W_D1_RE      A6F             1         W    RE   6  None          1
746  6W_D1_RE     B17D             1         W    RE   6  None          1
747     6W_D2    6A13A             1         W  None   6  None          2
748     6W_D2     6B10             2         W  None   6  None          2
749     6W_D2     6B12             2         W  None   6  None          2
750     6W_D2     6B13             2         W  None   6  None          2
751     6W_D2      6B6             1         W  None   6  None          2
752     6W_D2      6C3             1         W  None   6  None          2
753     6W_D2      6C4             2         W  None   6  None          2
754     6W_D2      6C5             2         W  None   6  None          2
755     6W_D2      6C6             2         W  None   6  None          2
756     6W_D2     8C4A             1         W  None   6  None          2
757     6W_D2     8C5A             1         W  None   6  None          2
758     6W_D2     8C6A             1         W  None   6  None          2
759     6W_D2     9C10             3         W  None   6  None          2
760     6W_D2      A19             1         W  None   6  None          2
761     6W_D2      B10             1         W  None   6  None          2
762     6W_D2      B11             1         W  None   6  None          2
763     6W_D2      B12             4         W  None   6  None          2
764     6W_D2      B37             1         W  None   6  None          2
765     6W_D2      B38             4         W  None   6  None          2
766     6W_D2     B38A             3         W  None   6  None          2
767     6W_D2      B42             2         W  None   6  None          2
768   6W_D2_1     6A3A             2         W  None   6  None          2
769   6W_D2_1      B12             1         W  None   6  None          2

[148 rows x 8 columns]